
services:
  backend:
    build: ./backend
    container_name: ortrta_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ortrta
      POSTGRES_USER: ortrta_user
      POSTGRES_PASSWORD: ortrta_password
    ports:
      - "5432:5432"