# Generated by Django 6.0.2 on 2026-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_lens_camera_lens_cameras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='cameras',
            field=models.ManyToManyField(blank=True, related_name='lenses', to='equipment.camera'),
        ),
    ]
