# Generated by Django 6.0.2 on 2026-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_lens_cameras'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='has_fixed_lens',
            field=models.BooleanField(default=False),
        ),
    ]
