# Generated by Django 6.0.2 on 2026-03-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_camera_has_fixed_lens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='fixed_lens_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='equipment.mount'),
        ),
        migrations.AddField(
            model_name='lens',
            name='mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lenses', to='equipment.mount'),
        ),
    ]
