# Generated by Django 6.0.2 on 2026-03-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_mount_camera_fixed_lens_model_camera_mount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lens',
            name='cameras',
        ),
    ]
