# Generated by Django 6.0.2 on 2026-03-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_lens_cameras'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='cameras',
            field=models.ManyToManyField(blank=True, related_name='lenses', to='equipment.camera'),
        ),
    ]
