# Generated by Django 6.0.4 on 2026-06-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_lens_cameras'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
