# Generated by Django 6.0.4 on 2026-06-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_camera_is_deleted'),
    ]

    operations = [
    ]
