# Generated by Django 6.0.2 on 2026-03-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0006_roll_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='type',
        ),
        migrations.AddField(
            model_name='roll',
            name='film_type',
            field=models.CharField(choices=[('COLOR_NEGATIVE', 'Négatif couleur'), ('BLACK_AND_WHITE', 'Noir et blanc'), ('COLOR_SLIDE', 'Diapositive couleur')], default='COLOR_NEGATIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='roll',
            name='format',
            field=models.CharField(choices=[('35MM-12', '35mm-12'), ('35MM-24', '35mm-24'), ('35MM-36', '35mm-36'), ('120-04 (6x17)', '120-04 (6x17)'), ('120-06 (6x12)', '120-06 (6x12)'), ('120-08 (6x9)', '120-08 (6x9)'), ('120-09 (6x8)', '120-09 (6x8)'), ('120-10 (6x7)', '120-10 (6x7)'), ('120-12 (6x6)', '120-12 (6x6)'), ('120-16 (645)', '120-16 (645)'), ('220-08 (6x17)', '220-08 (6x17)'), ('220-12 (6x12)', '220-12 (6x12)'), ('220-16 (6x9)', '220-16 (6x9)'), ('220-18 (6x8)', '220-18 (6x8)'), ('220-20 (6x7)', '220-20 (6x7)'), ('220-24 (6x6)', '220-24 (6x6)'), ('220-32 (645)', '220-32 (645)'), ('LARGE-4x5', 'Grand format 4x5'), ('LARGE-5x7', 'Grand format 5x7'), ('LARGE-8x10', 'Grand format 8x10'), ('110', '110'), ('126', '126'), ('127', '127')], default='35MM-36', max_length=20),
        ),
    ]
