# Generated by Django 6.0.2 on 2026-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0005_alter_roll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
