# Generated by Django 6.0.2 on 2026-03-04 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_lens_camera_lens_cameras'),
        ('rolls', '0007_remove_roll_qr_code_remove_roll_type_roll_film_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['user'], name='rolls_roll_user_id_5802d7_idx'),
        ),
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['status'], name='rolls_roll_status_1ec112_idx'),
        ),
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['date_start'], name='rolls_roll_date_st_348e10_idx'),
        ),
    ]
