name: CI

on:
    push:
        branches: [main]
    pull_request:

jobs:
    backend:
        runs-on: ubuntu-latest

        services:
          db:
            image: postgres:16
            env:
              POSTGRES_DB: ortrta
              POSTGRES_USER: ortrta_user
              POSTGRES_PASSWORD: ortrta_password
            ports:
              - 5432:5432
            options: >-
              --health-cmd "pg_isready -U ortrta_user -d ortrta"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
        
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_NAME: ortrta
          DB_USER: ortrta_user
          DB_PASSWORD: ortrta_password


        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install backend dependencies
              run: |
                cd backend
                pip install -r requirements.txt

            - name: Django check
              run: |
                cd backend
                python manage.py check

            - name: Wait for Postgres
              run: |
                sudo apt-get update
                sudo apt-get install -y postgresql-client
                until pg_isready -h 127.0.0.1 -p 5432 -U ortrta_user; do
                  sleep 1
                done
              env:
                PGPASSWORD: ortrta_password

            - name: Run migrations
              run: |
                cd backend
                python manage.py migrate

            - name: Run backend tests
              run: |
                cd backend
                python manage.py test

    frontend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                node-version: '22.13.1'

            - name: Install frontend dependencies
              run: |
                cd frontend
                npm install

            - name: Build frontend
              run: |
                cd frontend
                npm run build

            
            
